version: 0.0 # This is not a "version" number, do not change this line.
os: linux

files:
  - source: ./truebot-2.0
    destination: /home/ubuntu/
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
    - location: ./application_stop.sh
      timeout: 10
  BeforeInstall:
    - location: ./before_install.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: ./application_start.sh
      timeout: 10
