version: 0.0 # This is not a "version" number, do not change this line.
os: linux

files:
  - source: ./truebot
    destination: /home/ubuntu/
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 10
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 10
