version: 0.1 # This is not a "version" number, do not change this line.

phases:
  pre_build:
    commands:
      - echo "Running Prebuild Process..."
      - chmod +x ./scripts/pre_build.sh
      - ./scripts/pre_build.sh
  build:
    commands:
      - echo "Compiling..."
      - chmod +x ./scripts/build.sh
      - ./scripts/build.sh
  post_build:
    commands:
      - echo "Build completed on $(date)"
artifacts:
  files:
    - /go/src/truebot-2.0/truebot-2.0
    - appspec.yml
    - scripts/application_start.sh
    - scripts/before_install.sh
    - scripts/application_stop.sh
  discard-paths: yes
