version: 0.2 # This is not a "version" number, do not change this line.

phases:
  pre_build:
    commands:
      - echo "Running Prebuild Process..."
      - echo "Getting External Dependencies..."
      - go get github.com/fatih/color
      - go get github.com/bwmarrin/discordgo
      - go get github.com/mattn/go-sqlite3
      - go get github.com/jonas747/dca
      - go get -u github.com/rylio/ytdl
      - go get google.golang.org/api/googleapi/transport
      - go get google.golang.org/api/youtube/v3
      - echo "Creating $GOPATH/src/truebot-2.0"
      - mkdir -p $GOPATH/src/truebot-2.0
      - echo "Moving files to $GOPATH/src/truebot-2.0"
      - mv $CODEBUILD_SRC_DIR/*.go $GOPATH/src/truebot-2.0/
      - echo "Ready to compile."
      
  build:
    commands:
      - echo "Changing to $GOPATH/src/truebot-2.0 and compiling."
      - cd $GOPATH/src/truebot-2.0
      - go build
  post_build:
    commands:
      - mv $GOPATH/src/truebot-2.0/truebot-2.0 /root/truebot-2.0
      - echo "Build completed on $(date)"
artifacts:
  files:
    - /root/truebot-2.0
    - appspec.yml
    - scripts/application_start.sh
    - scripts/before_install.sh
    - scripts/application_stop.sh
  discard-paths: yes
